# Generated by Django 4.2.6 on 2023-10-18 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=255, verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, verbose_name='Nazwa ćwiczenia')),
                ('Description', models.TextField(verbose_name='Opis ćwiczenia')),
                ('ExcerciseLinkUrl', models.URLField(blank=True, null=True, verbose_name='Link do filmu')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrenerApp.excercisecategory', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Ćwiczenie',
                'verbose_name_plural': 'Ćwiczenia',
            },
        ),
    ]
