# Generated by Django 4.2.6 on 2023-10-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0002_excercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercise',
            name='NameEng',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nazwa ćwiczenia (ENG)'),
        ),
    ]
