# Generated by Django 4.2.6 on 2023-10-19 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0005_alter_person_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataPomiaru', models.DateField(verbose_name='Data pomiaru')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrenerApp.person', verbose_name='Osoba')),
            ],
            options={
                'verbose_name': 'Pomiar',
                'verbose_name_plural': 'Pomiary',
            },
        ),
    ]
