# Generated by Django 4.2.6 on 2023-10-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0007_rename_datapomiaru_measurement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='BFR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Poziom tkanki tłuszczowej w %'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='BodyWater',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Poziom wody w organiźmie w %'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='Growth',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Wzrost w cm'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='Weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Waga w kg'),
        ),
    ]
