# Generated by Django 4.2.6 on 2023-10-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0009_measurement_abdomen_measurement_chest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewsText', models.CharField(max_length=255, verbose_name='News')),
                ('NewsDate', models.DateField()),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
