# Generated by Django 4.2.6 on 2023-10-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0010_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercise',
            name='ImageBack',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Zdjęcie tylne aktony'),
        ),
        migrations.AddField(
            model_name='excercise',
            name='ImageFront',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Zdjęcie przednie aktony'),
        ),
        migrations.AddField(
            model_name='excercise',
            name='ImageSide',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Zdjęcie boczne aktony'),
        ),
    ]
