# Generated by Django 4.2.6 on 2023-10-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0011_excercise_imageback_excercise_imagefront_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercise',
            name='Name',
            field=models.CharField(max_length=300, verbose_name='Nazwa ćwiczenia'),
        ),
    ]
