# Generated by Django 4.2.6 on 2023-10-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0012_alter_excercise_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcerciseMuscles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=255, verbose_name='Grupa mięśni')),
            ],
            options={
                'verbose_name': 'Grupa mięśni',
                'verbose_name_plural': 'Grupy mięśni',
            },
        ),
        migrations.AddField(
            model_name='excercise',
            name='Muscles',
            field=models.ManyToManyField(to='TrenerApp.excercisemuscles', verbose_name='Grupy mięśni'),
        ),
    ]
