# Generated by Django 4.2.6 on 2023-10-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0013_excercisemuscles_excercise_muscles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excercisemuscles',
            old_name='CategoryName',
            new_name='MuscleName',
        ),
    ]
