# Generated by Django 4.2.6 on 2023-10-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0014_rename_categoryname_excercisemuscles_musclename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excercise',
            old_name='Muscles',
            new_name='DirectMus',
        ),
    ]
