# Generated by Django 4.2.6 on 2023-10-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0017_alter_measurement_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='Abdomen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Obwód brzucha w cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='BFR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poziom tkanki tłuszczowej w %'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='BodyWater',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poziom wody w organiźmie w %'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='Chest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Klatka piersiowa cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='Growth',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Wzrost w cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='Hips',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Biodra w cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='LeftArm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=' Lewe ramię w cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='LeftThigh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Lewe udo w cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='RightArm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Prawe ramię w cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='RightThigh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Prawe udo w cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='Waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talia w cm'),
        ),
    ]
