# Generated by Django 4.2.6 on 2023-10-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0018_alter_measurement_abdomen_alter_measurement_bfr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='Desc',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
    ]
