# Generated by Django 4.2.6 on 2023-10-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0019_measurement_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Opis modułu')),
                ('Type', models.CharField(choices=[('cardio', 'Cardio'), ('mobility', 'Mobility'), ('siłowy', 'Siłowy'), ('fbw', 'FBW')], default='Mobility', max_length=30, verbose_name='Typ modułu')),
            ],
            options={
                'verbose_name': 'Moduł',
                'verbose_name_plural': 'Moduły',
            },
        ),
    ]
