# Generated by Django 4.2.6 on 2023-10-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0020_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.PositiveIntegerField(default=0, verbose_name='Czas trwania ćwiczenia')),
                ('Repetitions', models.PositiveIntegerField(default=0, verbose_name='Ilość powtórzeń')),
                ('Exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrenerApp.excercise')),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrenerApp.module')),
            ],
            options={
                'verbose_name': 'Połączenie Moduł-Ćwiczenie',
                'verbose_name_plural': 'Połączenia Moduł-Ćwiczenie',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='Exercises',
            field=models.ManyToManyField(through='TrenerApp.ModuleExercise', to='TrenerApp.excercise'),
        ),
    ]
