# Generated by Django 4.2.6 on 2023-10-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0021_moduleexercise_module_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleexercise',
            name='Series',
            field=models.PositiveIntegerField(default=0, verbose_name='Ilość serii'),
        ),
        migrations.AddField(
            model_name='moduleexercise',
            name='Weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Ciężar na powtórzenie'),
        ),
        migrations.AlterField(
            model_name='moduleexercise',
            name='Duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Czas trwania ćwiczenia (jeśli dotyczy)'),
        ),
        migrations.AlterField(
            model_name='moduleexercise',
            name='Repetitions',
            field=models.PositiveIntegerField(default=0, verbose_name='Ilość powtórzeń w serii'),
        ),
    ]
