# Generated by Django 4.2.6 on 2023-10-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrenerApp', '0022_moduleexercise_series_moduleexercise_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='FullDescription',
            field=models.TextField(blank=True, null=True, verbose_name='Opis modułu'),
        ),
        migrations.AlterField(
            model_name='module',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nazwa modułu'),
        ),
    ]
